services:
  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - PROFILE=prd
      - DB_CONN_STR=mongodb://app:pass@mongo:27017/financialcontrol?authSource=admin
      - DB_NAME=financialcontrol
      - PORT=8080

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=app
      - MONGODB_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=financialcontrol
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db
      - type: bind
        source: ./init.js
        target: /docker-entrypoint-initdb.d/init.js

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_USERNAME: app
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
